# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Thomas Fishwick
description: >- # this means to ignore newlines until "baseurl:"
  Thomas Fishwick is a software developer and data scientist
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://link477.com' # the base hostname & protocol for your site, e.g. http://example.com
site_url: 'https://link477.com'
twitter_username: TomFishwick477
github_username: SL477
linkedin_username: thomas-fishwick-313459172
stackoverflow_username: 14416333/link477
kaggle_username: tomfishwick
datacamp_username: fishwickt
credly_username: thomas-fishwick.519c62f9
exercism_username: Link477
logo: /assets/images/link477.png
photo: /assets/images/tom.jpg
logo_width: 366
logo_height: 256
logo_alt: My logo of Link477 built in Lego
logo_webp: /assets/images/link477.webp

show_excerpts: true
show_comments: true

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
lsi: false
safe: true
incremental: false
highlighter: rouge
gist: noscript
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
sass:
  style: compressed

collections:
  notes:
    output: true
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - hint-report/
  - webp/
